"""SSZ size limits for the REST+SSZ Engine API."""

# Payload / envelope limits.
MAX_BYTES_PER_TX = 2**30
MAX_TXS_PER_PAYLOAD = 2**20
MAX_WITHDRAWALS_PER_PAYLOAD = 2**4
BYTES_PER_LOGS_BLOOM = 256
MAX_EXTRA_DATA_BYTES = 2**5
MAX_BAL_BYTES = MAX_BYTES_PER_TX
MAX_EXECUTION_REQUESTS_PER_PAYLOAD = 2**8
MAX_BYTES_PER_EXECUTION_REQUEST = MAX_BYTES_PER_TX

# Blob / cell limits
MAX_BLOB_COMMITMENTS_PER_BLOCK = 2**12
FIELD_ELEMENTS_PER_BLOB = 4096
BYTES_PER_FIELD_ELEMENT = 32
BYTES_PER_BLOB = FIELD_ELEMENTS_PER_BLOB * BYTES_PER_FIELD_ELEMENT
CELLS_PER_EXT_BLOB = 128
FIELD_ELEMENTS_PER_CELL = 64
BYTES_PER_CELL = FIELD_ELEMENTS_PER_CELL * BYTES_PER_FIELD_ELEMENT

# Blob-pool / bodies.
MAX_VERSIONED_HASHES_PER_REQUEST = 128
MAX_BLOBS_REQUEST = MAX_VERSIONED_HASHES_PER_REQUEST
MAX_BODIES_REQUEST = 2**5

# Status / error limits.
MAX_ERROR_BYTES = 1024

# Identity / capabilities limits.
MAX_CLIENT_CODE_LENGTH = 2
MAX_CLIENT_NAME_LENGTH = 64
MAX_CLIENT_VERSION_LENGTH = 64
MAX_CLIENT_VERSIONS = 4
MAX_CAPABILITY_NAME_LENGTH = 64
MAX_CAPABILITIES = 64
